version: latest

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit

  operator:
    image: 127.0.0.1:5000/operator
    build: 
      context: ./
      dockerfile: ./operator_service/Dockerfile
    networks: 
      - rabbit

  worker1:
    image: 127.0.0.1:5000/worker
    build: 
      context: ./
      dockerfile: ./worker_service/Dockerfile
    networks: 
      - rabbit

  # output:
  #   image: 127.0.0.1:5000/output
  #   build:
  #     context: ./
  #     dockerfile: ./output_service/Dockerfile
  #   volumes: 
  #     - .:/app/data
  #   networks: 
  #     - my_network

networks:
  rabbit: # This will create a network called `my_network`
    driver: bridge